  import Hackathon1 from "../assets/onchain-summer-awards.png";
  import Hackathon2 from "../assets/ai-innovation-challenge.png";
  import Hackathon3 from "../assets/devstart-bootcamp.png";
  import Hackathon4 from "../assets/codekickstart.png";
  import Hackathon5 from "../assets/mega-prize-hack.png";
  import Hackathon6 from "../assets/crypto-challenge-cup.png";
  import Hackathon7 from "../assets/ai-climate-hack.png";
  import Hackathon8 from "../assets/open-source-surge.png";
  import Hackathon9 from "../assets/remote-devfest.png";
  import Hackathon10 from "../assets/cyber-online.png";
  import Hackathon11 from "../assets/nextgen-hack.png";
  import Hackathon12 from "../assets/quick-start.png";


  const hackathons = [
    {
      id: 1,
      category: "featured",
      title: "Onchain Summer Awards",
      description:
        "Build. Launch. Scale. Earn. This summer's top web3 hackathon!",
      date: "Jul 9 – Aug 26, 2025",
      location: "Online",
      prize: "Rs. 250K+ in prizes",
      participants: "1,200+ registered",
      image: Hackathon1,
      deadline: "28d:11h:28m",
      tags: ["web3", "blockchain", "ethereum"],
    },
    {
      id: 2,
      category: "featured",
      title: "AI Innovation Challenge",
      description: "Build the next generation of AI applications",
      date: "Aug 15 – Sep 15, 2025",
      location: "Online & SF Finals",
      prize: "Rs. 100K in prizes",
      participants: "800+ registered",
      image: Hackathon2,
      deadline: "42d:05h:12m",
      tags: ["ai", "ml", "generative"],
    },
    {
      id: 3,
      category: "beginner",
      title: "DevStart Bootcamp",
      description: "A beginner-friendly hackathon to launch your dev journey",
      date: "Aug 10 – Aug 20, 2025",
      location: "Online",
      prize: "Rs. 10K in prizes",
      participants: "500+ registered",
      image: Hackathon3,
      deadline: "15d:04h:11m",
      tags: ["beginner", "frontend", "html"],
    },
    {
      id: 4,
      category: "beginner",
      title: "CodeKickstart",
      description: "Beginner focused challenge with mentorship",
      date: "Sep 1 – Sep 10, 2025",
      location: "Online",
      prize: "Rs. 5K in prizes",
      participants: "350+ registered",
      image: Hackathon4,
      deadline: "30d:10h:00m",
      tags: ["beginner", "html", "css"],
    },
    {
      id: 5,
      category: "prizes",
      title: "Mega Prize Hack",
      description: "Show off your skills and win big prizes! Hurry Up!",
      date: "Aug 25 – Sep 5, 2025",
      location: "Online",
      prize: "Rs. 500K in prizes",
      participants: "2,000+ registered",
      image: Hackathon5,
      deadline: "25d:05h:00m",
      tags: ["web", "cloud", "prize"],
    },
    {
      id: 6,
      category: "prizes",
      title: "Crypto Challenge Cup",
      description: "Blockchain and crypto-focused hackathon with big bounties",
      date: "Sep 10 – Sep 25, 2025",
      location: "Online",
      prize: "Rs. 300K in prizes",
      participants: "1,100+ registered",
      image: Hackathon6,
      deadline: "39d:08h:44m",
      tags: ["crypto", "security", "web3"],
    },
    {
      id: 7,
      category: "trending",
      title: "AI x Climate Hack",
      description: "Tackle climate change with the power of AI",
      date: "Aug 20 – Sep 10, 2025",
      location: "Online",
      prize: "Rs. 120K in prizes",
      participants: "1,000+ registered",
      image: Hackathon7,
      deadline: "33d:01h:33m",
      tags: ["ai", "climate", "ml"],
    },
    {
      id: 8,
      category: "trending",
      title: "Open Source Surge",
      description: "Contribute to open source and win big prizes",
      date: "Aug 28 – Sep 18, 2025",
      location: "Online",
      prize: "Rs. 80K in prizes",
      participants: "950+ registered",
      image: Hackathon8,
      deadline: "37d:22h:00m",
      tags: ["opensource", "devtools"],
    },
    {
      id: 9,
      category: "online",
      title: "Remote DevFest",
      description: "Build from anywhere, collaborate globally and win big!",
      date: "Sep 1 – Sep 30, 2025",
      location: "Online",
      prize: "Rs. 200K in prizes",
      participants: "1,300+ registered",
      image: Hackathon9,
      deadline: "45d:00h:00m",
      tags: ["remote", "global", "web"],
    },
    {
      id: 10,
      category: "online",
      title: "CyberSecure Online",
      description: "Online-only cybersecurity hackathon",
      date: "Aug 5 – Aug 25, 2025",
      location: "Online",
      prize: "Rs. 90K in prizes",
      participants: "720+ registered",
      image: Hackathon10,
      deadline: "20d:10h:50m",
      tags: ["security", "online", "tools"],
    },
    {
      id: 11,
      category: "soon",
      title: "NextGen Hack",
      description: "Starts in just a few days. Get ready!",
      date: "Aug 1 – Aug 10, 2025",
      location: "Online",
      prize: "Rs. 50K in prizes",
      participants: "600+ registered",
      image: Hackathon11,
      deadline: "3d:12h:00m",
      tags: ["soon", "startup", "mobile"],
    },
    {
      id: 12,
      category: "soon",
      title: "Quick Start Sprint",
      description: "Short hackathon, big ideas!",
      date: "Aug 2 – Aug 5, 2025",
      location: "Online",
      prize: "Rs. 20K in prizes",
      participants: "400+ registered",
      image: Hackathon12,
      deadline: "2d:22h:45m",
      tags: ["quick", "short", "launch"],
    },
  ];

  export default hackathons;